source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'KINWebBrowserExample.xcodeproj'
platform :ios, :deployment_target => '7.0'

target 'KINWebBrowserExample' do
	pod 'KINWebBrowser', :path => '../'
end
