source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'KINWebBrowserExample.xcodeproj'
platform :ios, :deployment_target => '7.0'

pod 'KINWebBrowser', :git => 'https://github.com/dfmuir/KINWebBrowser.git', :branch => 'dev'

